language: node_js

node_js:
  - '10'

env:
  global:
    - secure: "QD9/yC8mBxm1pDcjKYo2yikge+uFtbJFV8JKZqyDE+PyoPoBld44B8DbwdV9E3IGOiThLPJAXRbvaKziPBspBNuzbR2K1WICSoMOjooSlHjOkh4CzCnXNW1mFeY75Wz+TpqJifHPlC9PGrESA5BYHToWU6CH2SN5j0ihbQN+FoKsS4Q5zd3zMf6wzK2PUFwbhhTJJrD0m44zLxhEb3FRqXQK19Jedwtpcl7cSI8iRGBsQcOu3R9S+L6S0F2IzZaE2IZ4fRMW+bknkzyiv7HQkA7q43VlutjduyVUayeAstXc+FXiBdJD39gWi/JNbS2S9Fe1jLadG1CAkLQlFhZLDh7e/VfGI0e700CIyjHQlhhViBNJoPv47w5XESLKI728MtGk8yreyJzF2cgIdKtdH89mW1NW6w9usG1GEWnkD32hs+rRGuYS7t+EN62tFRRAfpEsLWdrwslKOzLcDN2YE5W1oKdfw2O2Zb0BkVLkpJvPW3kTERtNEfv/1O197wR82RpDTNf44584xz2rUbtJyF7T77S37YdG171sA8bktK1+NpDrS09fZASg3MdeevivCb0PrFenAFTdDklHRujeZweAG0zNSFCqNvkXCOSTuZ5Iywpr43VrJN6a5oaqrf7oyReTkj+sfi7CGzRdb/6g/f9G+GYq5olmlSyzXTBeu8M="
    - secure: "xOHGS36IjkBKRIg8UTHbrQ1fJkSo15ZznVGBSUH0xOC/nFIuuDM3R4bVLUXrkNWc8IciouDPlNKbLGx4Cn4v1lzqhni5GWxlKXKijF0OIuC5IPa5gJj9O60SsFrnN5F7LvlUjwCydU5XeJ3U/wtYtGsJ6DVtB+U2uf4hdwDXeU5mq3kIQfk4wJYYs7wIG2o1yyeRZxLs0ubs9rBzAtLSl0ZYVVJRFYlHuhQLkL6XNah2Bg1UAqZJ8t5lYXWx1GjGYRjkp84oIMbv24UYXtu3A71p5dDTICSa6D0WeRjZzUxvqDmt6YP03+zktNUAV0vdJg9WWMX69JOZwNJ6+/WCFlnqgRZVKzvoIdwtSt8xsHls2MQFFeInAeEqG0C0GTv8pGcFnduOjJCjyeab/YEMgS9kq98OoVEQdwqmV+bqgiBpLNRgNDM3PyCdfnQhU2a4d+V7aDVMIX4zU3oDqDCff9Rva4SetkAALspl/37zaGNl56OOJtwNPAkcWPJHd1Z8dWZUJsa3Mm844Rw+LgGdVZI6wEzJ7S4jTi6xAe3ucae/CJLpABAM4dNDmMrQn7fFhxsXA/EzmUrK2rsy2U+ZVng3Y8Ss0hM2KAQc6ZAFlJ5jmeA80Vx7jH/Ylq9OHBWawh81NKZ6yi8ee+a4gL08lK9BwJPT2+Rl8LTgibEPGic="

before_install:
  - npm install -D

script:
  - npm run build
  - npm run coverage
